// <auto-generated />
using Data.DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20220128113644_CreateDb")]
    partial class CreateDb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Core.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Image")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Image = "team-1.jpg",
                            IsDeleted = false,
                            Name = "Walter White",
                            Position = "Chief Executive Officer"
                        },
                        new
                        {
                            Id = 2,
                            Image = "team-2.jpg",
                            IsDeleted = false,
                            Name = "Sarah Jhonson",
                            Position = "Product Manager"
                        },
                        new
                        {
                            Id = 3,
                            Image = "team-3.jpg",
                            IsDeleted = false,
                            Name = "William Anderson",
                            Position = "CTO"
                        },
                        new
                        {
                            Id = 4,
                            Image = "team-4.jpg",
                            IsDeleted = false,
                            Name = "Amanda Jepson",
                            Position = "Accountant"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
